packages:
  - apps/*
  - packages/*
  - packages/themes/*
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@testing-library/react@16.3.3'
  - '@vitejs/plugin-react@6.1.1'
